#!/bin/bash
set -euo pipefail

# Local 4090 RWKV-7 comparison using the original LeWM/Mamba2 BPE8192 data
# condition:
#   tokenizer: fineweb_8192_bpe.model
#   train data: fineweb10B_sp8192
#   train tokens/step: 524,288
#   target train token budget: 6,090 steps, matching the 10-minute BPE LeWM run.
#
# Single-GPU runs emulate the official global batch via gradient accumulation.

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
ROOT_DIR="$(cd "$SCRIPT_DIR/../../.." && pwd)"
PYTHON="${PYTHON:-$ROOT_DIR/.venv/bin/python}"

cd "$SCRIPT_DIR"

RUN_ID="${RUN_ID:-record_rwkv_d576_l10_bpe8192}" \
TOKENIZER="${TOKENIZER:-bpe}" \
TOKENIZER_PATH="${TOKENIZER_PATH:-$ROOT_DIR/data/tokenizers/fineweb_8192_bpe.model}" \
VOCAB_SIZE="${VOCAB_SIZE:-8192}" \
DATA_PATH="${DATA_PATH:-$ROOT_DIR/data/datasets/fineweb10B_sp8192}" \
BACKBONE="${BACKBONE:-rwkv7}" \
RWKV_HEAD_SIZE="${RWKV_HEAD_SIZE:-64}" \
RWKV_BACKEND="${RWKV_BACKEND:-cuda}" \
RWKV_CHUNK_LEN="${RWKV_CHUNK_LEN:-16}" \
MODEL_DIM="${MODEL_DIM:-576}" \
NUM_LAYERS="${NUM_LAYERS:-10}" \
D_STATE="${D_STATE:-64}" \
D_CONV="${D_CONV:-4}" \
EXPAND="${EXPAND:-1}" \
MLP_EVERY="${MLP_EVERY:-2}" \
MLP_MULT="${MLP_MULT:-4}" \
ACTIVATION="${ACTIVATION:-relu2}" \
EMBED_DIM="${EMBED_DIM:-336}" \
PREDICTOR_HIDDEN_MULT="${PREDICTOR_HIDDEN_MULT:-4}" \
PROJECTOR_TYPE="${PROJECTOR_TYPE:-linear}" \
TIE_EMBEDDINGS="${TIE_EMBEDDINGS:-1}" \
LOGIT_SOFTCAP="${LOGIT_SOFTCAP:-15}" \
SOFTCAP_TYPE="${SOFTCAP_TYPE:-poly}" \
JEPA_WEIGHT="${JEPA_WEIGHT:-1.0}" \
JEPA_STEPS="${JEPA_STEPS:-3}" \
CE_WEIGHT="${CE_WEIGHT:-1.0}" \
SIGREG_LAMBDA="${SIGREG_LAMBDA:-1.0}" \
SIGREG_SCHEDULE="${SIGREG_SCHEDULE:-0}" \
DETACH_TARGETS="${DETACH_TARGETS:-0}" \
TRAIN_SEQ_LEN="${TRAIN_SEQ_LEN:-1024}" \
TRAIN_BATCH_TOKENS="${TRAIN_BATCH_TOKENS:-524288}" \
GRAD_ACCUM_STEPS="${GRAD_ACCUM_STEPS:-64}" \
ITERATIONS="${ITERATIONS:-6090}" \
WARMUP_STEPS="${WARMUP_STEPS:-10}" \
WARMDOWN_FRACTION="${WARMDOWN_FRACTION:-0.15}" \
MAX_WALLCLOCK_SECONDS="${MAX_WALLCLOCK_SECONDS:-0}" \
MATRIX_LR="${MATRIX_LR:-0.02}" \
SCALAR_LR="${SCALAR_LR:-0.01}" \
EMBED_LR="${EMBED_LR:-0.01}" \
MUON_BACKEND_STEPS="${MUON_BACKEND_STEPS:-3}" \
MUON_WD="${MUON_WD:-0.04}" \
ADAM_WD="${ADAM_WD:-0.05}" \
GRAD_CLIP_NORM="${GRAD_CLIP_NORM:-1.0}" \
QUANT_BITS="${QUANT_BITS:-4}" \
FP_STORAGE="${FP_STORAGE:-FP8}" \
QAT_FRACTION="${QAT_FRACTION:-1.0}" \
VAL_LOSS_EVERY="${VAL_LOSS_EVERY:-0}" \
VAL_BATCH_SIZE="${VAL_BATCH_SIZE:-65536}" \
TRAIN_LOG_EVERY="${TRAIN_LOG_EVERY:-100}" \
VAL_MAX_TOKENS="${VAL_MAX_TOKENS:-0}" \
TEMP_SCALING="${TEMP_SCALING:-1}" \
TEMP_CALIB="${TEMP_CALIB:-1.02}" \
SLIDING_EVAL="${SLIDING_EVAL:-1}" \
SLIDING_EVAL_STRIDE="${SLIDING_EVAL_STRIDE:-16}" \
SLIDING_BATCH_SIZE="${SLIDING_BATCH_SIZE:-64}" \
CHECKPOINT_EVERY="${CHECKPOINT_EVERY:-100}" \
CHECKPOINT_DIR="${CHECKPOINT_DIR:-./checkpoints_record_rwkv_d576_l10_bpe8192}" \
SEED="${SEED:-42}" \
COMPILE_MODE="${COMPILE_MODE:-default}" \
OMP_NUM_THREADS=1 "$PYTHON" "$SCRIPT_DIR/train_jepa_ssm.py"
