#!/bin/bash
# To JEPA Or Not To JEPA, That Is Le Question
# ============================================

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
ROOT_DIR="$(cd "$SCRIPT_DIR/../../.." && pwd)"
cd "$SCRIPT_DIR"

RUN_ID=run_lewm_jepa_rwkv7_bpe1024 \
TOKENIZER=bpe \
TOKENIZER_PATH="$ROOT_DIR/data/tokenizers/fineweb_1024_bpe.model" \
VOCAB_SIZE=1024 \
DATA_PATH="$ROOT_DIR/data/datasets/fineweb10B_sp1024" \
BACKBONE=rwkv7 \
RWKV_HEAD_SIZE=64 \
RWKV_BACKEND=cuda \
RWKV_CHUNK_LEN=16 \
MODEL_DIM=640 \
NUM_LAYERS=10 \
D_STATE=64 \
D_CONV=4 \
EXPAND=1 \
MLP_EVERY=2 \
MLP_MULT=4 \
ACTIVATION=relu2 \
EMBED_DIM=336 \
PREDICTOR_HIDDEN_MULT=4 \
PROJECTOR_TYPE=linear \
TIE_EMBEDDINGS=1 \
LOGIT_SOFTCAP=15 \
SOFTCAP_TYPE=poly \
JEPA_WEIGHT=1.0 \
JEPA_STEPS=3 \
CE_WEIGHT=1.0 \
SIGREG_LAMBDA=1.0 \
SIGREG_SCHEDULE=0 \
DETACH_TARGETS=0 \
TRAIN_SEQ_LEN=1024 \
TRAIN_BATCH_TOKENS=524288 \
ITERATIONS=10000 \
WARMUP_STEPS=10 \
WARMDOWN_FRACTION=0.15 \
MAX_WALLCLOCK_SECONDS=600 \
MATRIX_LR=0.02 \
SCALAR_LR=0.01 \
EMBED_LR=0.01 \
MUON_BACKEND_STEPS=3 \
MUON_WD=0.04 \
ADAM_WD=0.05 \
GRAD_CLIP_NORM=1.0 \
QUANT_BITS=4 \
FP_STORAGE=FP8 \
QAT_FRACTION=1.0 \
VAL_LOSS_EVERY=0 \
TRAIN_LOG_EVERY=1000 \
VAL_MAX_TOKENS=0 \
TEMP_SCALING=1 \
TEMP_CALIB=1.02 \
SLIDING_EVAL=1 \
SLIDING_EVAL_STRIDE=16 \
SLIDING_BATCH_SIZE=512 \
CHECKPOINT_EVERY=0 \
CHECKPOINT_DIR=./checkpoints \
SEED=42 \
COMPILE_MODE=default \
OMP_NUM_THREADS=1 torchrun --standalone --nproc_per_node=8 "$SCRIPT_DIR/train_jepa_ssm.py"
